# Generated by Django 4.0.2 on 2022-02-16 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('lend_id', models.IntegerField(blank=True, null=True)),
                ('lend_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
