# Generated by Django 4.0.2 on 2022-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_image_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name=999),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(max_length=499),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=99),
        ),
    ]
